[build]
target = "x86_64-unknown-uefi"
rustflags = ["-Z", "pre-link-args=/subsystem:efi_runtime_driver", "-C", "link-args=/debug:dwarf"]

[target.x86_64-unknown-uefi]
linker = "/usr/local/bin/lld-link-trace"
